runtime: nodejs12

service: mips

handlers:
  - url: /(.*\.(gif|png|svg|ttf|jpeg|jpg|css|css.map|js|js.map|pdf|scss|ico|json|json.map|mp4|webm|xml|html))$
    static_files: _site/\1
    secure: always
    upload: _site/(.*)
    http_headers:
      X-Frame-Options: deny
  - url: /
    static_files: _site/index.html
    secure: always
    upload: _site/index.html
    http_headers:
      X-Frame-Options: deny
  - url: /(.*)$
    static_files: _site/\1
    secure: always
    upload: _site/(.*)
    http_headers:
      X-Frame-Options: deny
